apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  POSTGRES_HOST: {{ .Values.config.POSTGRES_HOST | quote }}
  POSTGRES_PORT: {{ .Values.config.POSTGRES_PORT | quote }}
  POSTGRES_DB: {{ .Values.config.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.config.POSTGRES_USER | quote }}
  DJANGO_SETTINGS_MODULE: {{ .Values.config.DJANGO_SETTINGS_MODULE | quote }}
