image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.us-west-2.amazonaws.com/lesson-7-ecr
  tag: latest
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

replicaCount: 2

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  cpuUtilization: 70

ingress:
  enabled: true
  className: nginx
  host: myapp.example.com
  path: /
  pathType: Prefix
  tls: true
  clusterIssuer: letsencrypt-prod

config:
  POSTGRES_DB: myappdb
  POSTGRES_USER: myappuser
  POSTGRES_PASSWORD: myapppass
  SECRET_KEY: django-insecure-devops-homework-secret-key-change-in-production
  DJANGO_SETTINGS_MODULE: myapp.settings
